In [2]:
import numpy as np 

In [4]:
x = np.matrix(np.arange(1,17).reshape(4,4)) #Python arranges the elements row wise

In [5]:
x 

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [6]:
x[2:4,1:3] # To obtain values in a given range.R is 1-based and includes ending index, Python is 0 based and does not.

matrix([[10, 11],
        [14, 15]])

In [7]:
x[2:4,0:2] # Exercise : select 2x2 subsection from the "bottom left" of matrix 

matrix([[ 9, 10],
        [13, 14]])